name: Compile and upload vertex pipeline
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag:
        default: latest
        required: false
        type: string
      model_name:
        required: true
        type: string
    secrets:
      SERVICE_ACCOUNT_KEY:
        required: true


jobs:
  vertex-pipeline-compile-and-upload:
    name: Compile and Upload
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      ENVIRONMENT: ${{ inputs.environment }}
      PIPELINE_BUCKET: "gs://cd-ml-vertex-pipelines-${{ inputs.environment }}"
      MODEL_NAME: ${{ inputs.model_name }}
    steps:
      - name: pp
        run: "echo ${{ inputs.environment }}"
