name: "DEV Workflow"

on:
  workflow_dispatch:
    inputs:
      run-training:
        description: 'Run Training'
        required: false
        type: boolean


env:
  DAY_OF_WEEK: Monday


jobs:
  compile-vertex-pipeline-job:
    name: "Compile and Upload"
    uses: ./.github/workflows/actions.yml
    with:
      environment: "$DAY_OF_WEEK"
      model_name: "$DAY_OF_WEEK"
