name: Workflow

on:
  push:
    branches:
      - master

jobs:
  arbitrarily-named-workflow:
    uses: ./.github/workflows/actions.yml
    with:
      folder: "path/to"
      file_name: "hello-world.txt"
    secrets:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
