name: "DEV Workflow"

on:
  workflow_dispatch:
    inputs:
      run-training:
        description: 'Run Training'
        required: false
        type: boolean

env:
  DAY_OF_WEEK: Monday

jobs:
  compile-vertex-pipeline-job:
    name: "Compile and Upload"
    uses: ./.github/workflows/actions.yml
    with:
      environment: ${{ env.DAY_OF_WEEK }}
      model_name: ${{ env.DAY_OF_WEEK }}
