name: "DEV Workflow"

on:
  workflow_dispatch:
    inputs:
      run-training:
        description: 'Run Training'
        required: false
        type: boolean

env:
  ENVIRONMENT: dev
  PIPELINE_BUCKET: "gs://cd-ml-vertex-pipelines-dev"
  MODEL_NAME: sales_forecasting_delivery

jobs:
  compile-vertex-pipeline-job:
    name: "Compile and Upload"
    uses: ./.github/workflows/actions.yml
    with:
      environment: "${{ env.ENVIRONMENT }}"
      model_name: "${{ env.MODEL_NAME }}"
